// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkwkgaurfmudyingzmkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprd2tnYXVyZm11ZHlpbmd6bWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzc2NTEsImV4cCI6MjA2NDIxMzY1MX0.CcQ82UZlouHeVmUbkG8paa1v_2_FgUpF_q0cYoXi6PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);